In [1]:
import numpy as np

In [2]:
a=np.linspace(0,5,6)
a

array([0., 1., 2., 3., 4., 5.])

In [3]:
b=np.linspace(0,55,6)
b

array([ 0., 11., 22., 33., 44., 55.])

In [4]:
b=np.linspace(0,55,11)
b

array([ 0. ,  5.5, 11. , 16.5, 22. , 27.5, 33. , 38.5, 44. , 49.5, 55. ])

In [9]:
b=np.zeros(2)
b

array([0., 0.])

In [7]:
b=np.zeros((2,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b=np.zeros((6,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
c=np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
d=np.eye(4,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [13]:
c=np.array([[2,5,8,7],[3,1,9,0]])
c

array([[2, 5, 8, 7],
       [3, 1, 9, 0]])

In [14]:
y=np.sort(d,axis=1)
y

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [1]:
a=np.array([[1,2,1],[3,4,3],[5,6,5]])
b=np.array([[4,4,1],[4,4,2],[4,4,3]])
print('matrix multiplication:\n',np.matmul(a,b))

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
a=np.array([[1,2,1],[3,4,3],[5,6,5]])
b=np.array([[4,4,1],[4,4,2],[4,4,3]])
print('matrix multiplication:\n',np.matmul(a,b))

matrix multiplication:
 [[16 16  8]
 [40 40 20]
 [64 64 32]]


In [21]:
a=np.array([1,2,1],[3,4,3])
b=np.array([4,4],[4,4])
print('matrix multiplication:\n',np.matmul(b,a))

TypeError: Field elements must be 2- or 3-tuples, got '3'

#### print(a*b)

In [6]:
print(b*a)

[[ 4  8  1]
 [12 16  6]
 [20 24 15]]


In [7]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])

In [8]:
np.array_equal(a,b)

False

In [9]:
np.array_equal(a,c)

True

In [10]:
a=np.array([1,1,0,0], dtype=bool)
b=np.array([1,0,1,0], dtype=bool)
#np.logical_or(a,b)

array([ True,  True,  True, False])

In [13]:
a=np.array([1,1,0,0],dtype=int)
b=np.array([1,0,1,0],dtype=int)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [12]:
print(a+b)

[2 1 1 0]


In [15]:
a=np.array([1,2,4,0],dtype=int)
b=np.array([1,3,1,4],dtype=int)
np.logical_or(a,b)
print(a+b)

[2 5 5 4]


In [16]:
a=np.array([1,1,0,0],dtype=float)
b=np.array([1,0,1,0],dtype=float)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [17]:
print(a+b)

[2. 1. 1. 0.]


In [22]:
x.sum()

NameError: name 'x' is not defined

In [23]:
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [24]:
x.sum()

6

In [25]:
x.sum(axis=1)

array([2, 4])

In [26]:
x.sum(axis=0)

array([3, 3])

In [2]:
import numpy as np

In [3]:
random_array=np.random.randint(1,121,5)
print(random_array)

[ 70  40  34 102 114]


In [4]:
a=np.random.rand(4)
a

array([0.68974411, 0.1356496 , 0.86143838, 0.71858446])

In [5]:
a=np.random.rand(100)
a

array([0.60881991, 0.30146588, 0.40116527, 0.99365987, 0.67168781,
       0.65075872, 0.02840016, 0.86374273, 0.12758058, 0.1082554 ,
       0.46992985, 0.11479752, 0.25461441, 0.2500633 , 0.02446987,
       0.73883449, 0.22850207, 0.77678791, 0.80465815, 0.41269062,
       0.64095721, 0.69285555, 0.71257797, 0.03711832, 0.12233734,
       0.20227016, 0.42894558, 0.85588448, 0.57794295, 0.00376472,
       0.48819332, 0.44833628, 0.14220935, 0.1153149 , 0.35628292,
       0.17718332, 0.22893801, 0.34849667, 0.21733303, 0.04532417,
       0.86431509, 0.919509  , 0.40218327, 0.20524069, 0.81823238,
       0.49680556, 0.11912581, 0.05519056, 0.30702061, 0.70692992,
       0.89156293, 0.51145401, 0.27274251, 0.92893038, 0.02056373,
       0.90067665, 0.4894332 , 0.80587822, 0.74571332, 0.6024897 ,
       0.85481637, 0.43726725, 0.38358286, 0.32839833, 0.62639274,
       0.72405272, 0.60420869, 0.37712656, 0.21765982, 0.57779939,
       0.84803832, 0.45150905, 0.13290864, 0.71263705, 0.03550

In [6]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)
print(b)


[100   2   3]
[100   2   3]


In [8]:
arr=np.arange(25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [9]:
a1=arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print("shape of a:{}".format(a.shape))

[[1 2 3]
 [4 5 6]]
shape of a:(2, 3)


In [11]:
a= np.arange(0,101,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [12]:
a= np.array([1,2,3,4])
print(a)
print(a+1)

[1 2 3 4]
[2 3 4 5]


In [13]:
a**2

array([ 1,  4,  9, 16])

In [14]:
c=np.diag([])

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [16]:
a=np.arange(4)
a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [17]:
x=np.array([1,2,3,4])
np.sum(x)

10

In [18]:
x.sum(axis=0)

10

In [20]:
normal_array=np.arange(0,10,1)
print('array is',format(normal_array))
print('min element is',np.min(normal_array))
print('max element is',np.max(normal_array))
print('min element is',np.sum(normal_array))
print('mean element is',np.mean(normal_array))
print('median element is',np.median(normal_array))
print('snadard element is',np.std(normal_array))



array is [0 1 2 3 4 5 6 7 8 9]
min element is 0
max element is 9
min element is 45
mean element is 4.5
median element is 4.5
snadard element is 2.8722813232690143
